'use client'
import {Swiper,SwiperSlide} from 'swiper/react'
import {Autoplay,EffectFade,Pagination,Navigation} from 'swiper/modules'
import 'swiper/css';import 'swiper/css/effect-fade';import 'swiper/css/pagination';import 'swiper/css/navigation'
import {motion} from 'framer-motion'
const camps=[
 {id:'01',name:'TERELJ NOMAD',place:'Gorkhi–Terelj National Park',tag:'FOREST · RIVER · GER',image:'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=1800&q=85',desc:'Wake beneath granite cliffs, pine forests and wide Mongolian skies. A quiet base for slow mornings and wild afternoons.',facts:['70 km from Ulaanbaatar','Traditional gers','River-side setting']},
 {id:'02',name:'TERELJ HORIZON',place:'Terelj Valley',tag:'MOUNTAINS · SUNSET · SPACE',image:'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1800&q=85',desc:'An elevated escape where open valleys meet dramatic rock formations, designed for privacy, views and long sunsets.',facts:['Panoramic valley views','Private gers','Sunset decks']},
 {id:'03',name:'ELSEN TASARKHAI',place:'Elsen Tasarkhai',tag:'DUNES · STEPPE · SILENCE',image:'https://images.unsplash.com/photo-1472396961693-142e6e269027?auto=format&fit=crop&w=1800&q=85',desc:'Trade forest for golden dunes. Ride across the sand, meet the steppe at dusk and sleep under an enormous sky.',facts:['Golden sand dunes','Camel experiences','Stargazing']}
]
export default function CampSlider(){return <Swiper modules={[Autoplay,EffectFade,Pagination,Navigation]} effect="fade" loop autoplay={{delay:5500,disableOnInteraction:false}} pagination={{clickable:true}} navigation className="h-[78vh] min-h-[650px] w-full"><div className="absolute z-20 left-6 md:left-12 top-1/2 -translate-y-1/2 text-white pointer-events-none"><span className="text-xs tracking-[.35em] uppercase opacity-70">03 destinations · 01 journey</span></div>{camps.map(c=><SwiperSlide key={c.id}><div className="relative h-full w-full overflow-hidden"><motion.img initial={{scale:1.08}} whileInView={{scale:1}} transition={{duration:7,ease:'easeOut'}} src={c.image} alt={c.name} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-black/20"/><div className="absolute inset-x-0 bottom-0 p-6 md:p-12 lg:p-16 text-white"><div className="max-w-6xl mx-auto"><div className="flex items-end justify-between gap-8"><div><p className="mb-3 text-xs tracking-[.3em] uppercase text-white/70">{c.tag}</p><h3 className="text-5xl md:text-7xl lg:text-8xl font-semibold tracking-[-.05em] leading-[.86]">{c.name}</h3><p className="mt-5 max-w-xl text-sm md:text-base text-white/80 leading-7">{c.desc}</p></div><span className="hidden md:block text-[7rem] leading-none font-light text-white/20">{c.id}</span></div><div className="mt-8 flex flex-wrap gap-x-8 gap-y-3 border-t border-white/20 pt-5 text-xs uppercase tracking-[.16em] text-white/70">{c.facts.map(f=><span key={f}>{f}</span>)}</div></div></div></div></SwiperSlide>)}</Swiper>}
